name: notes1
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.4
  cached_network_image: ^3.0.0
  url_launcher: ^6.0.9
  provider: ^6.0.1
  dio_cache_interceptor: ^3.4.2
  sembast: ^3.4.9
  get: ^4.3.8
  sqflite: ^2.0.0+4
  shared_preferences: ^2.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
